# Generated by Django 4.1.7 on 2023-03-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familya', models.CharField(max_length=255)),
                ('kafedra', models.CharField(choices=[('aniq', 'Aniq fanlar'), ('tabiiy', 'Tabiiy fanlar'), ('maxsus', 'Maxsus fanlar')], max_length=10)),
                ('fan_nomi', models.CharField(max_length=255)),
                ('ilmiy_daraja', models.CharField(choices=[('dotsent', 'Dotsent'), ('doktor', 'Doktor'), ('magistr', 'Magistr')], max_length=255)),
            ],
        ),
    ]
