# Generated by Django 4.1.7 on 2023-03-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='ilmiy_daraja',
            field=models.CharField(choices=[('Dotsent', 'Dotsent'), ('Doktor', 'Doktor'), ('Magistr', 'Magistr')], max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='kafedra',
            field=models.CharField(choices=[('Aniq', 'Aniq fanlar'), ('Tabiiy', 'Tabiiy fanlar'), ('Maxsus', 'Maxsus fanlar')], max_length=10),
        ),
    ]
