# Generated by Django 4.1.7 on 2023-03-11 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_post_created_post_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
