# Generated by Django 4.1.7 on 2023-03-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_post_updated_alter_post_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
