# Generated by Django 4.1.7 on 2023-03-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_post_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Talaba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("second_name", models.CharField(max_length=255)),
                ("guruh_raqami", models.IntegerField(max_length=50)),
                ("fakultet_nomi", models.CharField(max_length=255)),
                ("ortacha_baho", models.IntegerField(max_length=255)),
            ],
        ),
    ]
